FROM ubuntu:18.04

RUN apt update


RUN apt install -y g++ \
         make \
         wget \
         unzip \
         vim \
         git \
         dstat \
         python3-pip


# install gcc-10
RUN apt install -y software-properties-common
RUN add-apt-repository -y ppa:ubuntu-toolchain-r/test
RUN apt update
RUN apt install -y gcc-10 g++-10
RUN update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 10
RUN update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 10

# install cmake 3.24
RUN wget https://github.com/Kitware/CMake/releases/download/v3.24.3/cmake-3.24.3-linux-x86_64.sh
RUN mkdir /opt/cmake
RUN sh cmake-3.24.3-linux-x86_64.sh --skip-license --prefix=/opt/cmake/
RUN ln -s /opt/cmake/bin/cmake /usr/local/bin/cmake

# install NASM
RUN wget https://www.nasm.us/pub/nasm/releasebuilds/2.15.05/nasm-2.15.05.tar.xz
RUN tar -xf nasm-2.15.05.tar.xz --strip-components=1
RUN ./configure --prefix=/usr && make
RUN make install

RUN apt-get update && apt-get install -y \
        software-properties-common
    RUN add-apt-repository ppa:deadsnakes/ppa
    RUN apt-get update && apt-get install -y \
        python3.7 \
        python3-pip
    RUN python3.7 -m pip install pip
    RUN apt-get update && apt-get install -y \
        python3-distutils \
        python3-setuptools
    RUN python3.7 -m pip install pip --upgrade pip

RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.6 1
RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.7 2


# install numpy and pytorch
RUN python3 -m pip install numpy
RUN python3 -m pip install torch==1.9.1+cpu -f https://download.pytorch.org/whl/torch_stable.html
